### ISSUE TITLE
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### ISSUE THREAD

**Issue by piervel** [MilaNLProc/feel-it#1]
* FEEL-IT version:
* Python version: Python 3.7.4
* Operating System: Windows

### Description

I'm trying to apply `feel_it` to several tweets stored in a csv file. (I'm using Jupyter.) The example explained by colab tutorial is very clear and I managed to replicate it without issues, but I'm having problems getting the emotion classification on my file. I obtained the error:

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### What I Did

```
import pandas as pd
df = pd.read_csv('file.csv',encoding='Windows-1252',usecols= ['text'])
type(df)
#pandas.core.frame.DataFrame
# Convert Python Pandas DataFrame To List
vals = df.values

# emetion classification:
from feel_it import EmotionClassifier, SentimentClassifier
emotion_classifier = EmotionClassifier()
emotion_classifier.predict(vals.tolist())
```

**Comment by vinid** [comment]
Hello @piervel!

Is the problem also happening on google colab on just on your local machine?

Can you share with me the result of 

`df.head()` 

just want to check what's inside the dataframe

**Comment by piervel** [comment]
Hello @vinid, thank you for your reply. This is a problem obtained on my local machine (and by using Jupyter). This is the result of `df.head()`:

![image](https://user-images.githubusercontent.com/48928538/121789879-07da7b00-cbda-11eb-9af1-516af0235a64.png)

**Comment by vinid** [comment]
Mmm when you do `df.values`, the dataframe is going to return a list of lists. Instead, feel-it wants just a list of strings.

Try a very simple thing:

```python
  vals = df["text"].values
  
  # emetion classification:
  from feel_it import EmotionClassifier, SentimentClassifier
  emotion_classifier = EmotionClassifier()
  emotion_classifier.predict(vals.tolist())

**Comment by piervel** [comment]
Thank you! It works for me :-)

**Comment by Gautamshahi** [comment]
What is the final solution? I  have tried few of them, it didn't work

**Comment by vinid** [comment]
Hello! You should give to the model a list of strings :)
