### ISSUE TITLE
Neutral class in Sentiment Classification

### ISSUE THREAD

**Issue by jacopo-repossi** [MilaNLProc/feel-it#2]
* FEEL-IT version: 1.0.3
* Python version: 3.7.8
* Operating System: Windows 10

### Description
Hi there, 
I was trying to use your library and first of all, good job!

Since I'm interest in Sentiment Analysis, I was following the documentation and trying to implement a "Neutral" class based on the model's outputs.
As I was experimenting, I noticed that no matter was I was trying to classify, it is almost impossible to get two probabilities such as it is feasible to implement a threshold like `if probs < threshold then "neutral"`
Here an example with a neutral sentence like "Today is Tuesday"
```
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("MilaNLProc/feel-it-italian-sentiment")
model = AutoModelForSequenceClassification.from_pretrained("MilaNLProc/feel-it-italian-sentiment")

sentence = 'Oggi è Martedì'
inputs = tokenizer(sentence, return_tensors="pt")

# Call the model and get the logits
labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
outputs = model(**inputs, labels=labels)
loss, logits = outputs[:2]
logits = logits.squeeze(0)

# Extract probabilities
proba = torch.nn.functional.softmax(logits, dim=0)

# Unpack the tensor to obtain negative and positive probabilities
negative, positive = proba
print(f"Probabilities: Negative {np.round(negative.item(),4)} - Positive {np.round(positive.item(),4)}")
```
Output: `Probabilities: Negative 0.0003 - Positive 0.9997`

I was expecting something like `Negative 0.4 - Positive 0.6` so that I could work with a possibile threshold.

Any idea why this is happening? Any suggestion on how I could solve this problem?
I also tested sentences like "Il muro è bianco", "Questo è un tavolo per appoggiare dei libri"...results are consistend with the above one..

I guess this could be relevant also in the main class `SentimentClassifier` since not all sentences are either Positive or Negative.

Thank you!

**Comment by vinid** [comment]
Hi @jacopo-repossi,

yes, the classifier is very skewed towards the two classes. To improve the performance we are right now working on an extended version of the dataset that also contains the "neutral" values.

I do not have a practical solution at the moment, but I can share the data with you (send me an email) and you can combine this with other dataset if needed
